### ISSUE TITLE
Installation fails with Python 3.12

### ISSUE THREAD

**Issue by nialov** [IntroQG/gradertools#1]
If you do not specify the Python version during `conda` installation, you will end up with Python 3.12 as the interpreter. However, `nose` has not been updated to support 3.12, or at least the `conda-forge` version. Consequently, you will end up with errors when importing `nose`:

~~~
>>> import nose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nialov/projects/geo-python-2024-instructor/.mamba/envs/geo-python-no-python-restrict/lib/python3.12/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/nialov/projects/geo-python-2024-instructor/.mamba/envs/geo-python-no-python-restrict/lib/python3.12/site-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/home/nialov/projects/geo-python-2024-instructor/.mamba/envs/geo-python-no-python-restrict/lib/python3.12/site-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/home/nialov/projects/geo-python-2024-instructor/.mamba/envs/geo-python-no-python-restrict/lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
ModuleNotFoundError: No module named 'imp'
~~~

To circumvent this, I used the following `environment.yaml`, which restricts Python to 3.11 at the latest:

~~~yaml
name: geo-python-2024-instructor

channels:
  - conda-forge

dependencies:
  - python >=3.8,<3.12
  - jupyter
  - notebook
  - nbgrader
  - jinja2
  - pandas
  - nose
  - gitpython
  - matplotlib
~~~

**Comment by davewhipp** [comment]
Thanks for noting this, @nialov. We recommend using the environment files at https://github.com/geo-python/python-environments/ for setting things up, which coincidentally have a pinned version of Python 3.11.

**Comment by nialov** [comment]
Ah, we simply missed the guidance linking there :D. Might I however suggest that you add a link to that repository in the `README.md` of this repository and replace the old guidance on installation within this repo? I can also do a PR, if wanted.
